version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./database:/app/database # Monta la cartella database per persistenza
      - ./app:/app               # Monta il codice per sviluppo live
    environment:
      - FLASK_ENV=development